// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/line.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/line.go -destination=internal/repository/mocks/line_mock.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	model "github.com/kevinmarcellius/torana-schedule/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockLineRepository is a mock of LineRepository interface.
type MockLineRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLineRepositoryMockRecorder
	isgomock struct{}
}

// MockLineRepositoryMockRecorder is the mock recorder for MockLineRepository.
type MockLineRepositoryMockRecorder struct {
	mock *MockLineRepository
}

// NewMockLineRepository creates a new mock instance.
func NewMockLineRepository(ctrl *gomock.Controller) *MockLineRepository {
	mock := &MockLineRepository{ctrl: ctrl}
	mock.recorder = &MockLineRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLineRepository) EXPECT() *MockLineRepositoryMockRecorder {
	return m.recorder
}

// GetLinesAndStations mocks base method.
func (m *MockLineRepository) GetLinesAndStations() ([]model.TrainTrip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinesAndStations")
	ret0, _ := ret[0].([]model.TrainTrip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinesAndStations indicates an expected call of GetLinesAndStations.
func (mr *MockLineRepositoryMockRecorder) GetLinesAndStations() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinesAndStations", reflect.TypeOf((*MockLineRepository)(nil).GetLinesAndStations))
}
