// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/schedule.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/schedule.go -destination=internal/repository/mocks/schedule_mock.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	model "github.com/kevinmarcellius/torana-schedule/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockScheduleRepository is a mock of ScheduleRepository interface.
type MockScheduleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleRepositoryMockRecorder
	isgomock struct{}
}

// MockScheduleRepositoryMockRecorder is the mock recorder for MockScheduleRepository.
type MockScheduleRepositoryMockRecorder struct {
	mock *MockScheduleRepository
}

// NewMockScheduleRepository creates a new mock instance.
func NewMockScheduleRepository(ctrl *gomock.Controller) *MockScheduleRepository {
	mock := &MockScheduleRepository{ctrl: ctrl}
	mock.recorder = &MockScheduleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleRepository) EXPECT() *MockScheduleRepositoryMockRecorder {
	return m.recorder
}

// GetAllSchedules mocks base method.
func (m *MockScheduleRepository) GetAllSchedules() ([]model.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSchedules")
	ret0, _ := ret[0].([]model.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSchedules indicates an expected call of GetAllSchedules.
func (mr *MockScheduleRepositoryMockRecorder) GetAllSchedules() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSchedules", reflect.TypeOf((*MockScheduleRepository)(nil).GetAllSchedules))
}

// SearchSchedules mocks base method.
func (m *MockScheduleRepository) SearchSchedules(params *model.ScheduleSearchParams) ([]model.Schedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchSchedules", params)
	ret0, _ := ret[0].([]model.Schedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchSchedules indicates an expected call of SearchSchedules.
func (mr *MockScheduleRepositoryMockRecorder) SearchSchedules(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchSchedules", reflect.TypeOf((*MockScheduleRepository)(nil).SearchSchedules), params)
}
