// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/station.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/station.go -destination=internal/repository/mocks/station_mock.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	model "github.com/kevinmarcellius/torana-schedule/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockStationRepository is a mock of StationRepository interface.
type MockStationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStationRepositoryMockRecorder
	isgomock struct{}
}

// MockStationRepositoryMockRecorder is the mock recorder for MockStationRepository.
type MockStationRepositoryMockRecorder struct {
	mock *MockStationRepository
}

// NewMockStationRepository creates a new mock instance.
func NewMockStationRepository(ctrl *gomock.Controller) *MockStationRepository {
	mock := &MockStationRepository{ctrl: ctrl}
	mock.recorder = &MockStationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStationRepository) EXPECT() *MockStationRepositoryMockRecorder {
	return m.recorder
}

// GetStationsAndSchedulesByLine mocks base method.
func (m *MockStationRepository) GetStationsAndSchedulesByLine(lineName string) ([]model.StationScheduleData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStationsAndSchedulesByLine", lineName)
	ret0, _ := ret[0].([]model.StationScheduleData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStationsAndSchedulesByLine indicates an expected call of GetStationsAndSchedulesByLine.
func (mr *MockStationRepositoryMockRecorder) GetStationsAndSchedulesByLine(lineName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStationsAndSchedulesByLine", reflect.TypeOf((*MockStationRepository)(nil).GetStationsAndSchedulesByLine), lineName)
}
