// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/trip.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/trip.go -destination=internal/repository/mocks/trip_mock.go -package=mock_repository
//

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	reflect "reflect"

	model "github.com/kevinmarcellius/torana-schedule/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockTripRepository is a mock of TripRepository interface.
type MockTripRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTripRepositoryMockRecorder
	isgomock struct{}
}

// MockTripRepositoryMockRecorder is the mock recorder for MockTripRepository.
type MockTripRepositoryMockRecorder struct {
	mock *MockTripRepository
}

// NewMockTripRepository creates a new mock instance.
func NewMockTripRepository(ctrl *gomock.Controller) *MockTripRepository {
	mock := &MockTripRepository{ctrl: ctrl}
	mock.recorder = &MockTripRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTripRepository) EXPECT() *MockTripRepositoryMockRecorder {
	return m.recorder
}

// GetAllTrips mocks base method.
func (m *MockTripRepository) GetAllTrips() ([]model.TrainTrip, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTrips")
	ret0, _ := ret[0].([]model.TrainTrip)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTrips indicates an expected call of GetAllTrips.
func (mr *MockTripRepositoryMockRecorder) GetAllTrips() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTrips", reflect.TypeOf((*MockTripRepository)(nil).GetAllTrips))
}
